# Generated by Django 3.1.7 on 2021-02-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=30)),
                ('player_url', models.CharField(max_length=120)),
                ('short_name', models.CharField(max_length=30)),
                ('club_name', models.CharField(max_length=50)),
            ],
        ),
    ]
